### ISSUE TITLE
Error "page_pagetype is required"

### ISSUE THREAD

**Issue by kohki-shikata** [hissy/addon_cif_importer#1]
> "page_name","page_path","page_pagetype","page_template","attr_meta_keywords","attr_exclude_sitemapxml","attr_select_tags","block_Main/content"
> "Lorem","/lorem","page","right_sidebar","Lorem, Ipsum",0,"hello//world","Lorem ipsum dolor sit amet, >consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
> "Ipsum","/about/ipsum","page","left_sidebar",,1,"hello",
> "Dolor","/lorem/dolor","page","full",,,,

Just copied and pasted to simple csv file, then imported, an error message displayed
"Exception page_pagetype is required."
![2015-10-02 13 25 50](https://cloud.githubusercontent.com/assets/4133263/10239481/30bd96e0-6909-11e5-9f2a-95b98b76bf07.png)

**Comment by hissy** [comment]
↓のレポジトリのissueですよね。

https://github.com/hissy/addon_csv_xml_converter

というわけで、クローズします。
